spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BLOCCA_DB_URL}/blocca
    username: ${BLOCCA_DB_USERNAME}
    password: ${BLOCCA_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
cors:
  allowed-origins: https://www.blocca.run
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted